import Head from "next/head";
import { Inter } from "@next/font/google";
import { Header } from "@/components/Header";
import {
  Box,
  Button,
  ButtonGroup,
  Container,
  GridItem,
  Heading,
  Highlight,
  HStack,
  Img,
  Spacer,
  Stack,
  Text,
  useBreakpointValue,
  VStack,
  Wrap,
  WrapItem,
} from "@chakra-ui/react";
import { Image, Link } from "@chakra-ui/next-js";
import { FaFacebook, FaInstagram, FaLinkedin } from "react-icons/fa";
import { getToken } from "@/services/user.service";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const token = getToken();

  return (
    <>
      <Head>
        <title>SolarCoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Box position="relative">
          {/* Background image */}
          <Box
            position="absolute"
            width="100%"
            height="100%"
            left="0"
            right="0"
            top="0"
            zIndex={-1}
            filter="blur(2px) contrast(0.8) brightness(1.2)"
          >
            <img
              src="landing/solarcell.png"
              width="100%"
              style={{
                objectFit: "cover",
                height: "100%",
              }}
            />
          </Box>

          {/* Hero text */}
          <Container maxW={"3xl"} paddingTop="10vw">
            <VStack
              id="introduction"
              textAlign="center"
              filter="drop-shadow(0px 0px 8px rgba(255, 255, 255, 0.5))"
            >
              <Heading
                lineHeight="120%"
                letterSpacing="tighter"
                fontSize={{ base: "4xl", md: "6xl" }}
              >
                <Highlight query={"Net-Zero"} styles={{ color: "green.600" }}>
                  Let’s Take an Action to Net-Zero&nbsp;Together
                </Highlight>
              </Heading>
              <Text
                my={3}
                fontSize={{ base: "md", md: "xl" }}
                letterSpacing="tight"
              >
                Introducing Solar CC, the revolutionary carbon-credit based
                currency designed to pave&nbsp;the&nbsp;way for a greener
                future.
              </Text>

              <ButtonGroup p="6vw" display="flex" gap={8} colorScheme="green">
                <Button
                  as={Link}
                  color="black"
                  borderRadius="full"
                  width={150}
                  size="lg"
                  href={"/auth/retail"}
                  border="2px solid black"
                >
                  <Text fontSize="xl">Individuals</Text>
                </Button>

                <Button
                  as={Link}
                  color="black"
                  borderRadius="full"
                  width={150}
                  size="lg"
                  href={"/auth/sme"}
                  border="2px solid black"
                >
                  <Text>SMEs</Text>
                </Button>
              </ButtonGroup>
            </VStack>
          </Container>
        </Box>

        <VStack textAlign="center" p={16} m="auto" bg="#FFED9433">
          <Heading fontWeight="bold">What Solar CC Can Do</Heading>
          <Wrap spacing={64} justify="center" p={16}>
            <WrapItem flexDirection="column" gap={4}>
              <Img boxSize={192} objectFit="contain" src="/landing/car.png" />
              <Heading size="md">Offset Transportation</Heading>
            </WrapItem>
            <WrapItem flexDirection="column" gap={4}>
              <Img boxSize={192} objectFit="contain" src="/landing/hotel.png" />
              <Heading size="md">Offset Your Activity</Heading>
            </WrapItem>
          </Wrap>

          <Text>and much more</Text>
          <Button
            as={Link}
            href="/project"
            size="lg"
            px={32}
            bg="black"
            colorScheme="blackAlpha"
          >
            Explore
          </Button>
        </VStack>

        <VStack textAlign="center" p={16} m="auto" bg="#9DC17766">
          <Heading fontWeight="bold">What We Done</Heading>
          <Stack
            width="100%"
            justify="space-evenly"
            py={16}
            direction={{ base: "column", md: "row" }}
          >
            <VStack spacing={4}>
              <Img
                boxSize={192}
                objectFit="contain"
                src="/landing/co2.png"
                alt={"co2"}
              />
              <Heading size="md">9999 tCO2e Offset</Heading>
            </VStack>
            <VStack spacing={4}>
              <Img
                boxSize={192}
                objectFit="contain"
                src="/landing/student.png"
                alt={"individual"}
              />
              <Heading size="md">134 Green Individuals</Heading>
            </VStack>
            <VStack spacing={4}>
              <Img
                boxSize={192}
                objectFit="contain"
                src="/landing/paper-bag.png"
                alt={"smes"}
              />
              <Heading size="md">69 Carbon Neutral SMEs</Heading>
            </VStack>
          </Stack>
        </VStack>

        <VStack textAlign="center" py={16} m="auto" gap={8} bg="#FFED9433">
          <Heading fontWeight="bold">
            Calculate Your Carbon Footprint{" "}
            <Button colorScheme="green" variant="link" fontSize="3xl">
              Here!
            </Button>
          </Heading>
          <Link href="http://www.tgo.or.th/2020/index.php/th/post/thai-carbon-footprint-calculator-627">
            <Img
              boxSize={256}
              objectFit="contain"
              src="/landing/calculator.png"
              alt="carbon footprint"
            />
          </Link>
        </VStack>

        <VStack textAlign="center" py={16} m="auto" gap={8}>
          <Heading fontWeight="bold" color="green.500">
            2 Easy Steps to Offset
          </Heading>
          <Stack
            spacing={10}
            justify="center"
            // direction={{ base: "column", md: "row" }}
            direction="column"
          >
            <WrapItem alignItems="center" gap={4}>
              <Img
                boxSize={128}
                objectFit="contain"
                src="/landing/cart.png"
                alt="purchase"
                bg="yellow.100"
                rounded={16}
              />
              <Heading size={{ base: "sm", md: "md" }}>
                1. Purchase Solar Carbon Credit
              </Heading>
            </WrapItem>
            <WrapItem alignItems="center" gap={4}>
              <Img
                boxSize={128}
                objectFit="contain"
                src="/landing/cert.png"
                alt="certificate"
                bg="yellow.100"
                rounded={16}
              />
              <Heading size={{ base: "sm", md: "md" }}>
                2. Get Certificate
              </Heading>
            </WrapItem>
          </Stack>

          <Button
            as={Link}
            href={token ? "/store/solar-cc" : "/auth/choose"}
            colorScheme="green"
          >
            Click Here to Purchase
          </Button>
        </VStack>

        <Partners />

        <VStack textAlign="center" p={16} bg="#FFED9433">
          <Heading fontWeight="bold">
            Got questions? We’re here to help!
          </Heading>
          <Text>Our highly available team is always ready to help you.</Text>
          <Button colorScheme="gray" px={16} mt={8}>
            Contact us
          </Button>
        </VStack>

        <VStack
          pt={8}
          pb={4}
          px={8}
          gap={4}
          alignItems="flex-start"
          bg="#9DC17766"
        >
          <HStack>
            <Img boxSize={16} src="/favicon.png" />
            <Heading color="green.400" fontSize={{ sm: "md", md: "xl" }}>
              Solar CC
            </Heading>
          </HStack>

          <Text>
            221B baker street, Bangkok, Thailand 10555
            <br />
            +66 9 9999 9999
          </Text>
          <Spacer />
          <Box>
            <Text>Follow Us</Text>
            <HStack>
              <FaFacebook size={32} />
              <FaInstagram size={32} />
              <FaLinkedin size={32} />
            </HStack>
          </Box>
          <Spacer />
          <Text>© 2023 Solar CC Company Limited. All Rights Reserved</Text>
        </VStack>
      </main>
    </>
  );
}

const partners = [
  {
    name: "Escopolis",
    src: "landing/Escopolis Logo.png",
    href: "https://escopolis.co.th",
  },
  {
    name: "Exim Bank",
    src: "landing/Exim logo.webp",
    href: "https://www.exim.go.th",
  },
  {
    name: "CEO",
    src: "landing/CEO logo.png",
    href: "http://www.efe.or.th",
  },
  {
    name: "Gideon One",
    src: "landing/gideon one logo.jpg",
    href: "https://www.gideon-one.com",
  },
  {
    name: "TGO",
    src: "landing/TGO logo.jpg",
    href: "http://www.tgo.or.th/2020/index.php/th/",
  },
];
const Partners = () => {
  // Break partners into potentially multiple rows
  const n = partners.length;
  const b = Math.ceil(n / 2);
  const partnerRows = useBreakpointValue({
    base: [partners.slice(0, b), partners.slice(b)],
    md: [partners],
  });

  return (
    <VStack textAlign="center" py={16} gap={8} bg="#E6F0F4">
      <Heading fontWeight="bold">Our Partners</Heading>
      {partnerRows?.map((partners) => (
        <HStack gap={8}>
          {partners.map(({ src, href }) => (
            <GridItem>
              <Link href={href}>
                <Img
                  boxSize={128}
                  objectFit="contain"
                  src={src}
                  bg="whiteAlpha.800"
                />
              </Link>
            </GridItem>
          ))}
        </HStack>
      ))}
    </VStack>
  );
};
