/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API Document
 * API Document Description
 * OpenAPI spec version: 1.0
 */
export interface SolarGenerateRequestDTO {
  /** Carbon Credit Serial Number */
  ccSerial: string;
}

export interface ResendEmailDto {
  /** User's email */
  email: string;
  /** User's id */
  id: number;
}

export interface LoginRequest {
  /** User's email */
  email?: string;
  /** User's name */
  name?: number;
  /** User's password */
  password: string;
}

/**
 * SMEs' size
 */
export type RegisterUserSMEsRequestSize =
  (typeof RegisterUserSMEsRequestSize)[keyof typeof RegisterUserSMEsRequestSize];

export const RegisterUserSMEsRequestSize = {
  SMALL: "SMALL",
  MEDIUM: "MEDIUM",
} as const;

/**
 * SMEs' type
 */
export type RegisterUserSMEsRequestIndustry =
  (typeof RegisterUserSMEsRequestIndustry)[keyof typeof RegisterUserSMEsRequestIndustry];

export const RegisterUserSMEsRequestIndustry = {
  MANUFACTURE: "MANUFACTURE",
  TRADE: "TRADE",
  SERVICE: "SERVICE",
} as const;

export interface RegisterUserSMEsRequest {
  /** User's email */
  email: string;
  /** User's password */
  password: string;
  /** User's name */
  name: number;
  /** User's telephone number */
  phone: string;
  /** SMEs' type */
  industry: RegisterUserSMEsRequestIndustry;
  /** SMEs' size */
  size: RegisterUserSMEsRequestSize;
}

export interface RegisterUserRetailRequest {
  /** User's email */
  email: string;
  /** User's password */
  password: string;
  /** User's name */
  name: number;
  /** User's telephone number */
  phone: string;
}
